export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';

export const USERPROFILE_UPDATE_REQUEST = "USERPROFILE_UPDATE_REQUEST";
export const USERPROFILE_UPDATE_SUCCESS = "USERPROFILE_UPDATE_SUCCESS";
export const USERPROFILE_UPDATE_FAIL = "USERPROFILE_UPDATE_FAIL";



